package com.example.coderem

data class LCdata(
    val status: String,
    val ranking: String,
    val total_problems_submitted: String,
    val total_problems_solved: String,
    val acceptance_rate: String,
    val easy_problems_submitted: String,
    val easy_questions_solved: String,
    val easy_acceptance_rate: String,
    val total_easy_questions: String,
    val medium_problems_submitted: String,
    val medium_questions_solved: String,
    val medium_acceptance_rate: String,
    val total_medium_questions: String,
    val hard_problems_submitted: String,
    val hard_questions_solved: String,
    val hard_acceptance_rate: String,
    val total_hard_questions: String,
    val contribution_points: String,
    val contribution_problems: String,
    val contribution_testcases: String,
    val reputation: String,
)